spring:
  application:
    name: spring-security
  jpa:
    # Provide database platform that is being used
    properties:
      hibernate-dialect=org:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:

      # New database is created when application starts and destroyed when application is stopped
      ddl-auto: update
      # Show sql when spring data jpa performs query
      format_sql: true
    show-sql: true

  datasource:
    # URL connection to database (spring-security is database name)
    url: jdbc:mysql://localhost:3307/micro_db?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root

token:
  jwt:
    secretKey: 413F4428472783999G9329HND9032MPENKSE9UND0303900291NNE0DNQ9WQWN0239NDE94B6250655368566D5970337336763979244226452948404D6351

server:
  port: 8083